from backend.database import SessionLocal, engine
from backend.models import Base, Recipe

RECIPES = [
    # ---------- DESAYUNO ----------
    {
        "nombre": "Huevos a la mexicana con tortilla de maíz",
        "imagen_url": "https://images.unsplash.com/photo-1583552336796-531290f1fe2a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=600",
        "tiempo_comida": "Desayuno",
        "goal_tags": ["bulk", "maintenance"],
        "categoria_tags": ["Alto en proteína"],
        "ingredientes": [
            {"alimento": "Huevo entero", "cantidad_g": 120},
            {"alimento": "Jitomate picado", "cantidad_g": 60},
            {"alimento": "Cebolla picada", "cantidad_g": 20},
            {"alimento": "Chile serrano picado", "cantidad_g": 10},
            {"alimento": "Tortilla de maíz", "cantidad_g": 60},
        ],
        "instrucciones": "Sofríe cebolla y chile, agrega jitomate hasta que suelte jugo, incorpora el huevo batido y cocina revolviendo. Sirve con tortillas calientes.",
        "kcal_aprox": 320,
    },
    {
        "nombre": "Claras revueltas con espinaca y avena",
        "imagen_url": "https://images.unsplash.com/photo-1787761460248-672823a370dc?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=600",
        "tiempo_comida": "Desayuno",
        "goal_tags": ["cut"],
        "categoria_tags": ["Bajo en grasa", "Alto en proteína"],
        "ingredientes": [
            {"alimento": "Clara de huevo", "cantidad_g": 200},
            {"alimento": "Espinaca fresca", "cantidad_g": 60},
            {"alimento": "Avena en hojuelas", "cantidad_g": 40},
            {"alimento": "Leche descremada", "cantidad_g": 150},
        ],
        "instrucciones": "Cocina las claras con la espinaca salteada. Aparte, prepara la avena con la leche descremada a fuego bajo por 5 minutos.",
        "kcal_aprox": 280,
    },
    {
        "nombre": "Chilaquiles verdes con pollo deshebrado",
        "imagen_url": "https://images.unsplash.com/photo-1633372363856-f2fe2669a26e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=600",
        "tiempo_comida": "Desayuno",
        "goal_tags": ["maintenance", "bulk"],
        "ingredientes": [
            {"alimento": "Tostadas horneadas", "cantidad_g": 60},
            {"alimento": "Salsa verde", "cantidad_g": 100},
            {"alimento": "Pechuga de pollo deshebrada", "cantidad_g": 100},
            {"alimento": "Queso panela", "cantidad_g": 30},
            {"alimento": "Crema light", "cantidad_g": 15},
        ],
        "instrucciones": "Calienta la salsa verde, agrega las tostadas y mezcla rápido para que no se remojen de más. Sirve con pollo, queso y crema.",
        "kcal_aprox": 420,
    },
    {
        "nombre": "Licuado de avena, plátano y proteína",
        "imagen_url": "https://images.unsplash.com/photo-1712056407284-c1eda76e7bcd?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=600",
        "tiempo_comida": "Desayuno",
        "goal_tags": ["bulk"],
        "ingredientes": [
            {"alimento": "Avena en hojuelas", "cantidad_g": 50},
            {"alimento": "Plátano", "cantidad_g": 120},
            {"alimento": "Leche entera", "cantidad_g": 250},
            {"alimento": "Crema de cacahuate", "cantidad_g": 20},
        ],
        "instrucciones": "Licúa todos los ingredientes hasta obtener una mezcla homogénea. Sirve frío.",
        "kcal_aprox": 520,
    },
    # ---------- COLACIÓN ----------
    {
        "nombre": "Yogur griego con fresas y nuez",
        "imagen_url": "https://images.unsplash.com/photo-1641494587136-eec74f1944ae?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=600",
        "tiempo_comida": "Colación",
        "goal_tags": ["cut", "maintenance"],
        "ingredientes": [
            {"alimento": "Yogur griego descremado", "cantidad_g": 150},
            {"alimento": "Fresa", "cantidad_g": 80},
            {"alimento": "Nuez", "cantidad_g": 10},
        ],
        "instrucciones": "Mezcla el yogur con las fresas picadas y agrega la nuez encima.",
        "kcal_aprox": 150,
    },
    {
        "nombre": "Jícama y pepino con limón y chile piquín",
        "imagen_url": "https://images.unsplash.com/photo-1579636859960-06732cdccdf3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=600",
        "tiempo_comida": "Colación",
        "goal_tags": ["cut"],
        "ingredientes": [
            {"alimento": "Jícama", "cantidad_g": 100},
            {"alimento": "Pepino", "cantidad_g": 100},
            {"alimento": "Limón", "cantidad_g": 15},
            {"alimento": "Chile piquín", "cantidad_g": 2},
        ],
        "instrucciones": "Corta la jícama y el pepino en bastones, rocía con limón y chile piquín al gusto.",
        "kcal_aprox": 60,
    },
    {
        "nombre": "Malteada de proteína con almendras",
        "imagen_url": "https://images.unsplash.com/photo-1508061253366-f7da158b6d46?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=600",
        "tiempo_comida": "Colación",
        "goal_tags": ["bulk"],
        "categoria_tags": ["Alto en proteína", "Nuevas"],
        "ingredientes": [
            {"alimento": "Proteína en polvo", "cantidad_g": 30},
            {"alimento": "Leche entera", "cantidad_g": 250},
            {"alimento": "Almendra", "cantidad_g": 15},
        ],
        "instrucciones": "Licúa la proteína con la leche y las almendras hasta integrar bien.",
        "kcal_aprox": 300,
    },
    # ---------- COMIDA ----------
    {
        "nombre": "Pechuga a la plancha con arroz integral y verduras al vapor",
        "imagen_url": "https://images.unsplash.com/photo-1532550907401-a500c9a57435?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=600",
        "tiempo_comida": "Comida",
        "goal_tags": ["cut", "maintenance"],
        "categoria_tags": ["Bajo en grasa", "Alto en proteína"],
        "ingredientes": [
            {"alimento": "Pechuga de pollo", "cantidad_g": 150},
            {"alimento": "Arroz integral cocido", "cantidad_g": 100},
            {"alimento": "Brócoli", "cantidad_g": 100},
            {"alimento": "Zanahoria", "cantidad_g": 60},
            {"alimento": "Aceite de oliva", "cantidad_g": 8},
        ],
        "instrucciones": "Sazona y cocina la pechuga a la plancha. Cuece el brócoli y la zanahoria al vapor. Sirve con arroz integral y un hilo de aceite de oliva.",
        "kcal_aprox": 480,
    },
    {
        "nombre": "Caldo de res con verduras y elote",
        "imagen_url": "https://images.unsplash.com/photo-1665593998976-d957f2827fe7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=600",
        "tiempo_comida": "Comida",
        "goal_tags": ["maintenance"],
        "ingredientes": [
            {"alimento": "Chambarete de res", "cantidad_g": 130},
            {"alimento": "Elote", "cantidad_g": 100},
            {"alimento": "Calabacita", "cantidad_g": 80},
            {"alimento": "Zanahoria", "cantidad_g": 60},
            {"alimento": "Papa", "cantidad_g": 80},
        ],
        "instrucciones": "Cuece la carne en agua con sal hasta suavizar, agrega las verduras y cocina hasta que estén tiernas.",
        "kcal_aprox": 450,
    },
    {
        "nombre": "Bistec de res con papa al horno y ensalada",
        "imagen_url": "https://images.unsplash.com/photo-1785695691259-3f09db710535?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=600",
        "tiempo_comida": "Comida",
        "goal_tags": ["bulk"],
        "ingredientes": [
            {"alimento": "Bistec de res", "cantidad_g": 180},
            {"alimento": "Papa", "cantidad_g": 150},
            {"alimento": "Lechuga", "cantidad_g": 60},
            {"alimento": "Jitomate", "cantidad_g": 60},
            {"alimento": "Aceite de oliva", "cantidad_g": 10},
        ],
        "instrucciones": "Cocina el bistec a la plancha al término deseado. Hornea la papa hasta suavizar. Sirve con ensalada aderezada con aceite de oliva.",
        "kcal_aprox": 620,
    },
    {
        "nombre": "Pescado a la veracruzana con arroz blanco",
        "imagen_url": "https://images.unsplash.com/photo-1665332195309-9d75071138f0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=600",
        "tiempo_comida": "Comida",
        "goal_tags": ["cut", "maintenance"],
        "ingredientes": [
            {"alimento": "Filete de pescado blanco", "cantidad_g": 150},
            {"alimento": "Jitomate", "cantidad_g": 100},
            {"alimento": "Aceitunas", "cantidad_g": 15},
            {"alimento": "Cebolla", "cantidad_g": 30},
            {"alimento": "Arroz blanco cocido", "cantidad_g": 80},
        ],
        "instrucciones": "Prepara un sofrito de jitomate, cebolla y aceitunas; cocina el pescado dentro de la salsa a fuego medio hasta que esté cocido. Sirve con arroz.",
        "kcal_aprox": 420,
    },
    {
        "nombre": "Frijoles de la olla con queso y tortilla",
        "imagen_url": "https://images.unsplash.com/photo-1617990590988-895fe6cbabda?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=600",
        "tiempo_comida": "Comida",
        "goal_tags": ["maintenance", "bulk"],
        "ingredientes": [
            {"alimento": "Frijol negro cocido", "cantidad_g": 150},
            {"alimento": "Queso panela", "cantidad_g": 40},
            {"alimento": "Tortilla de maíz", "cantidad_g": 60},
            {"alimento": "Cilantro", "cantidad_g": 5},
        ],
        "instrucciones": "Calienta los frijoles, sirve con queso panela desmoronado, cilantro picado y tortillas.",
        "kcal_aprox": 400,
    },
    # ---------- CENA ----------
    {
        "nombre": "Ensalada de atún con verduras frescas",
        "imagen_url": "https://images.unsplash.com/photo-1578687388049-079580e6eb2d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=600",
        "tiempo_comida": "Cena",
        "goal_tags": ["cut"],
        "categoria_tags": ["Bajo en grasa", "Ensaladas"],
        "ingredientes": [
            {"alimento": "Atún en agua", "cantidad_g": 100},
            {"alimento": "Lechuga", "cantidad_g": 80},
            {"alimento": "Jitomate", "cantidad_g": 60},
            {"alimento": "Pepino", "cantidad_g": 60},
            {"alimento": "Aceite de oliva", "cantidad_g": 8},
        ],
        "instrucciones": "Mezcla todos los vegetales picados con el atún escurrido y adereza con aceite de oliva y limón al gusto.",
        "kcal_aprox": 250,
    },
    {
        "nombre": "Quesadillas de flor de calabaza",
        "imagen_url": "https://images.unsplash.com/photo-1618040996337-56904b7850b9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=600",
        "tiempo_comida": "Cena",
        "goal_tags": ["maintenance"],
        "ingredientes": [
            {"alimento": "Tortilla de maíz", "cantidad_g": 90},
            {"alimento": "Flor de calabaza", "cantidad_g": 60},
            {"alimento": "Queso Oaxaca", "cantidad_g": 50},
            {"alimento": "Epazote", "cantidad_g": 5},
        ],
        "instrucciones": "Rellena las tortillas con flor de calabaza salteada, queso y epazote; cocina en comal hasta que el queso funda.",
        "kcal_aprox": 380,
    },
    {
        "nombre": "Sopa de fideo con pechuga desmenuzada",
        "imagen_url": "https://images.unsplash.com/photo-1695088223408-cd5ae3b2b7fa?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=600",
        "tiempo_comida": "Cena",
        "goal_tags": ["bulk", "maintenance"],
        "ingredientes": [
            {"alimento": "Fideo", "cantidad_g": 60},
            {"alimento": "Pechuga de pollo deshebrada", "cantidad_g": 80},
            {"alimento": "Jitomate", "cantidad_g": 60},
            {"alimento": "Zanahoria", "cantidad_g": 40},
        ],
        "instrucciones": "Fríe ligeramente el fideo, agrega caldo con jitomate licuado y zanahoria, cocina hasta suavizar y añade el pollo.",
        "kcal_aprox": 350,
    },
    {
        "nombre": "Tacos de nopal con queso panela",
        "imagen_url": "https://images.unsplash.com/photo-1564767655658-4e6b365884ff?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=600",
        "tiempo_comida": "Cena",
        "goal_tags": ["cut"],
        "ingredientes": [
            {"alimento": "Nopal cocido", "cantidad_g": 120},
            {"alimento": "Queso panela", "cantidad_g": 40},
            {"alimento": "Tortilla de maíz", "cantidad_g": 60},
            {"alimento": "Salsa roja", "cantidad_g": 30},
        ],
        "instrucciones": "Calienta el nopal cocido, sirve en tortillas con queso panela y salsa al gusto.",
        "kcal_aprox": 280,
    },
    # ---------- ENSALADAS ----------
    {
        "nombre": "Ensalada mediterránea con queso feta",
        "imagen_url": "https://images.unsplash.com/photo-1670237735381-ac5c7fa72c51?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=600",
        "tiempo_comida": "Comida",
        "goal_tags": ["cut", "maintenance"],
        "categoria_tags": ["Ensaladas", "Bajo en grasa"],
        "ingredientes": [
            {"alimento": "Lechuga romana", "cantidad_g": 100},
            {"alimento": "Jitomate cherry", "cantidad_g": 80},
            {"alimento": "Pepino", "cantidad_g": 60},
            {"alimento": "Aceitunas negras", "cantidad_g": 20},
            {"alimento": "Queso feta", "cantidad_g": 30},
            {"alimento": "Aceite de oliva", "cantidad_g": 8},
        ],
        "instrucciones": "Mezcla las verduras picadas, agrega el queso feta desmoronado y las aceitunas, adereza con aceite de oliva y orégano.",
        "kcal_aprox": 290,
    },
    {
        "nombre": "Ensalada de nopales con queso panela",
        "imagen_url": "https://images.unsplash.com/photo-1628961915037-a829e926e26e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=600",
        "tiempo_comida": "Comida",
        "goal_tags": ["cut"],
        "categoria_tags": ["Ensaladas", "Bajo en grasa"],
        "ingredientes": [
            {"alimento": "Nopal cocido", "cantidad_g": 150},
            {"alimento": "Jitomate", "cantidad_g": 60},
            {"alimento": "Cebolla morada", "cantidad_g": 20},
            {"alimento": "Cilantro", "cantidad_g": 5},
            {"alimento": "Queso panela", "cantidad_g": 40},
        ],
        "instrucciones": "Mezcla el nopal cocido con jitomate, cebolla y cilantro picados; agrega el queso panela en cubos y sazona con limón.",
        "kcal_aprox": 210,
    },
    {
        "nombre": "Ensalada de quinoa con pollo y aguacate",
        "imagen_url": "https://images.unsplash.com/photo-1712594534008-b1f94349f969?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=600",
        "tiempo_comida": "Comida",
        "goal_tags": ["maintenance", "bulk"],
        "categoria_tags": ["Ensaladas", "Alto en proteína"],
        "ingredientes": [
            {"alimento": "Quinoa cocida", "cantidad_g": 100},
            {"alimento": "Pechuga de pollo a la plancha", "cantidad_g": 120},
            {"alimento": "Aguacate", "cantidad_g": 50},
            {"alimento": "Jitomate cherry", "cantidad_g": 60},
        ],
        "instrucciones": "Combina la quinoa con el pollo desmenuzado, aguacate en cubos y jitomate cherry; adereza con limón y sal al gusto.",
        "kcal_aprox": 420,
    },
    {
        "nombre": "Ensalada César ligera con pollo",
        "imagen_url": "https://images.unsplash.com/photo-1550304943-4f24f54ddde9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=600",
        "tiempo_comida": "Comida",
        "goal_tags": ["cut", "maintenance"],
        "categoria_tags": ["Ensaladas"],
        "ingredientes": [
            {"alimento": "Lechuga romana", "cantidad_g": 120},
            {"alimento": "Pechuga de pollo a la plancha", "cantidad_g": 120},
            {"alimento": "Queso parmesano", "cantidad_g": 15},
            {"alimento": "Crutones integrales", "cantidad_g": 20},
            {"alimento": "Aderezo César light", "cantidad_g": 20},
        ],
        "instrucciones": "Corta la lechuga y mezcla con el pollo desmenuzado, queso parmesano y crutones; agrega el aderezo al final.",
        "kcal_aprox": 340,
    },
    # ---------- KETO ----------
    {
        "nombre": "Aguacate relleno de atún con mayonesa",
        "imagen_url": "https://images.unsplash.com/photo-1715611935696-a59ebf388252?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=600",
        "tiempo_comida": "Comida",
        "goal_tags": ["cut"],
        "categoria_tags": ["Keto", "Bajo en grasa"],
        "ingredientes": [
            {"alimento": "Aguacate", "cantidad_g": 150},
            {"alimento": "Atún en agua", "cantidad_g": 100},
            {"alimento": "Mayonesa", "cantidad_g": 15},
            {"alimento": "Apio picado", "cantidad_g": 20},
        ],
        "instrucciones": "Corta el aguacate a la mitad y retira un poco de pulpa; mezcla con atún, mayonesa y apio, y rellena las mitades.",
        "kcal_aprox": 380,
    },
    # ---------- NAVIDAD ----------
    {
        "nombre": "Pavo navideño con vegetales asados",
        "imagen_url": "https://images.unsplash.com/photo-1574672281194-db420378032d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=600",
        "tiempo_comida": "Cena",
        "goal_tags": ["maintenance", "bulk"],
        "categoria_tags": ["Navidad", "Alto en proteína"],
        "ingredientes": [
            {"alimento": "Pechuga de pavo horneada", "cantidad_g": 150},
            {"alimento": "Ejotes", "cantidad_g": 80},
            {"alimento": "Zanahoria baby", "cantidad_g": 80},
            {"alimento": "Arándano deshidratado", "cantidad_g": 15},
        ],
        "instrucciones": "Hornea la pechuga de pavo sazonada con hierbas. Asa los vegetales con un poco de aceite de oliva y decora con arándanos.",
        "kcal_aprox": 410,
    },
    {
        "nombre": "Ponche de frutas sin azúcar añadida",
        "imagen_url": "https://images.unsplash.com/photo-1669632851802-9d4672f4c55d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=600",
        "tiempo_comida": "Colación",
        "goal_tags": ["cut", "maintenance"],
        "categoria_tags": ["Navidad", "Bajo en grasa"],
        "ingredientes": [
            {"alimento": "Guayaba", "cantidad_g": 100},
            {"alimento": "Manzana", "cantidad_g": 100},
            {"alimento": "Caña", "cantidad_g": 60},
            {"alimento": "Canela en raja", "cantidad_g": 3},
            {"alimento": "Tejocote", "cantidad_g": 60},
        ],
        "instrucciones": "Hierve todas las frutas con la canela por 20 minutos. Sirve caliente sin azúcar añadida.",
        "kcal_aprox": 120,
    },
    # ---------- LOTE 1 (Mis catálogos) ----------
    # Desayuno
    {
        "nombre": "Omelette de queso panela y champiñones",
        "imagen_url": "https://images.unsplash.com/photo-1618173726624-99dd7db65b40?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=600",
        "tiempo_comida": "Desayuno",
        "goal_tags": ["cut", "maintenance"],
        "categoria_tags": ["Alto en proteína", "Nuevas"],
        "ingredientes": [
            {"alimento": "Huevo entero", "cantidad_g": 100},
            {"alimento": "Champiñón fileteado", "cantidad_g": 70},
            {"alimento": "Queso panela", "cantidad_g": 40},
            {"alimento": "Cebolla picada", "cantidad_g": 15},
        ],
        "instrucciones": "Saltea champiñones y cebolla hasta suavizar. Bate el huevo, agrégalo a la sartén y espolvorea el queso panela antes de doblar el omelette.",
        "kcal_aprox": 290,
    },
    {
        "nombre": "Hot cakes de avena y plátano sin harina",
        "imagen_url": "https://images.unsplash.com/photo-1598259298632-e785684cfa90?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=600",
        "tiempo_comida": "Desayuno",
        "goal_tags": ["maintenance", "bulk"],
        "categoria_tags": ["Nuevas"],
        "ingredientes": [
            {"alimento": "Avena en hojuelas", "cantidad_g": 60},
            {"alimento": "Plátano", "cantidad_g": 100},
            {"alimento": "Huevo entero", "cantidad_g": 50},
            {"alimento": "Canela en polvo", "cantidad_g": 2},
        ],
        "instrucciones": "Licúa todos los ingredientes hasta obtener una masa homogénea. Cocina pequeñas porciones en sartén antiadherente por ambos lados.",
        "kcal_aprox": 340,
    },
    {
        "nombre": "Yogur con granola casera y moras azules",
        "imagen_url": "https://images.unsplash.com/photo-1641536885341-301aeb52f1c0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=600",
        "tiempo_comida": "Desayuno",
        "goal_tags": ["cut", "maintenance"],
        "categoria_tags": ["Alto en proteína"],
        "ingredientes": [
            {"alimento": "Yogur griego descremado", "cantidad_g": 180},
            {"alimento": "Granola casera sin azúcar", "cantidad_g": 30},
            {"alimento": "Moras azules", "cantidad_g": 60},
            {"alimento": "Miel de abeja", "cantidad_g": 10},
        ],
        "instrucciones": "Sirve el yogur en un tazón, agrega la granola y las moras encima, y termina con un hilo de miel.",
        "kcal_aprox": 260,
    },
    {
        "nombre": "Huevos al horno con jitomate y espinaca",
        "imagen_url": "https://images.unsplash.com/photo-1624355311781-49422b771021?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=600",
        "tiempo_comida": "Desayuno",
        "goal_tags": ["cut"],
        "categoria_tags": ["Bajo en grasa", "Alto en proteína"],
        "ingredientes": [
            {"alimento": "Huevo entero", "cantidad_g": 100},
            {"alimento": "Jitomate en rodajas", "cantidad_g": 80},
            {"alimento": "Espinaca fresca", "cantidad_g": 50},
            {"alimento": "Aceite de oliva", "cantidad_g": 5},
        ],
        "instrucciones": "Coloca espinaca y jitomate en un refractario, casca los huevos encima y hornea a 180°C por 12-15 minutos hasta que cuaje la clara.",
        "kcal_aprox": 240,
    },
    {
        "nombre": "Papaya con yogur y semillas de chía",
        "imagen_url": "https://images.unsplash.com/photo-1666181941657-eade2d78f3fd?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=600",
        "tiempo_comida": "Desayuno",
        "goal_tags": ["cut", "maintenance"],
        "categoria_tags": ["Bajo en grasa"],
        "ingredientes": [
            {"alimento": "Papaya picada", "cantidad_g": 200},
            {"alimento": "Yogur natural bajo en grasa", "cantidad_g": 120},
            {"alimento": "Semillas de chía", "cantidad_g": 10},
        ],
        "instrucciones": "Sirve la papaya en un tazón, cubre con el yogur y espolvorea las semillas de chía. Deja reposar 5 minutos antes de comer.",
        "kcal_aprox": 180,
    },
    {
        "nombre": "Smoothie verde de espinaca, piña y chía",
        "imagen_url": "https://images.unsplash.com/photo-1610622929746-ab2606cfd2b7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=600",
        "tiempo_comida": "Desayuno",
        "goal_tags": ["cut", "maintenance"],
        "categoria_tags": ["Bajo en grasa", "Nuevas"],
        "ingredientes": [
            {"alimento": "Espinaca fresca", "cantidad_g": 40},
            {"alimento": "Piña picada", "cantidad_g": 100},
            {"alimento": "Plátano", "cantidad_g": 60},
            {"alimento": "Semillas de chía", "cantidad_g": 8},
            {"alimento": "Agua", "cantidad_g": 200},
        ],
        "instrucciones": "Licúa todos los ingredientes hasta obtener una mezcla homogénea. Sirve de inmediato.",
        "kcal_aprox": 190,
    },
    # Colación
    {
        "nombre": "Manzana con crema de almendra",
        "imagen_url": "https://images.unsplash.com/photo-1642339800118-eb551cfa1434?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=600",
        "tiempo_comida": "Colación",
        "goal_tags": ["cut", "maintenance"],
        "categoria_tags": ["Bajo en grasa"],
        "ingredientes": [
            {"alimento": "Manzana", "cantidad_g": 150},
            {"alimento": "Crema de almendra natural", "cantidad_g": 15},
        ],
        "instrucciones": "Corta la manzana en rebanadas y sirve con la crema de almendra para untar.",
        "kcal_aprox": 150,
    },
    {
        "nombre": "Mix de nueces y arándanos deshidratados",
        "imagen_url": "https://images.unsplash.com/photo-1543158181-1274e5362710?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=600",
        "tiempo_comida": "Colación",
        "goal_tags": ["maintenance", "bulk"],
        "categoria_tags": [],
        "ingredientes": [
            {"alimento": "Nuez", "cantidad_g": 15},
            {"alimento": "Almendra", "cantidad_g": 10},
            {"alimento": "Arándano deshidratado", "cantidad_g": 15},
        ],
        "instrucciones": "Mezcla todos los ingredientes en un contenedor pequeño. Ideal para llevar como colación entre comidas.",
        "kcal_aprox": 190,
    },
    {
        "nombre": "Palitos de jícama con limón y chile",
        "imagen_url": "https://images.unsplash.com/photo-1695088224158-f07345e58940?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=600",
        "tiempo_comida": "Colación",
        "goal_tags": ["cut"],
        "categoria_tags": ["Bajo en grasa"],
        "ingredientes": [
            {"alimento": "Jícama en palitos", "cantidad_g": 200},
            {"alimento": "Limón", "cantidad_g": 15},
            {"alimento": "Chile piquín en polvo", "cantidad_g": 2},
        ],
        "instrucciones": "Corta la jícama en palitos, rocía con jugo de limón y espolvorea el chile piquín.",
        "kcal_aprox": 55,
    },
    {
        "nombre": "Queso panela con guayaba",
        "imagen_url": "https://images.unsplash.com/photo-1615865417491-9941019fbc00?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=600",
        "tiempo_comida": "Colación",
        "goal_tags": ["cut", "maintenance"],
        "categoria_tags": ["Alto en proteína"],
        "ingredientes": [
            {"alimento": "Queso panela", "cantidad_g": 50},
            {"alimento": "Guayaba", "cantidad_g": 100},
        ],
        "instrucciones": "Corta el queso panela en cubos y sirve junto con la guayaba en rebanadas.",
        "kcal_aprox": 160,
    },
    {
        "nombre": "Edamame al vapor con sal de mar",
        "imagen_url": "https://images.unsplash.com/photo-1611810174991-5cdd99a2c6b2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=600",
        "tiempo_comida": "Colación",
        "goal_tags": ["cut", "maintenance"],
        "categoria_tags": ["Alto en proteína", "Bajo en grasa"],
        "ingredientes": [
            {"alimento": "Edamame con vaina", "cantidad_g": 150},
            {"alimento": "Sal de mar", "cantidad_g": 2},
        ],
        "instrucciones": "Cuece el edamame al vapor por 5 minutos, escurre y espolvorea sal de mar antes de servir.",
        "kcal_aprox": 130,
    },
    # Comida
    {
        "nombre": "Pechuga rellena de espinaca y queso panela",
        "imagen_url": "https://images.unsplash.com/photo-1641898378548-ac93da99786a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=600",
        "tiempo_comida": "Comida",
        "goal_tags": ["cut", "maintenance"],
        "categoria_tags": ["Alto en proteína", "Bajo en grasa"],
        "ingredientes": [
            {"alimento": "Pechuga de pollo", "cantidad_g": 200},
            {"alimento": "Espinaca fresca", "cantidad_g": 50},
            {"alimento": "Queso panela", "cantidad_g": 30},
            {"alimento": "Arroz integral cocido", "cantidad_g": 100},
        ],
        "instrucciones": "Abre la pechuga en mariposa, rellena con espinaca y queso, cierra con palillos y hornea 25 minutos a 180°C. Sirve con arroz integral.",
        "kcal_aprox": 420,
    },
    {
        "nombre": "Salmón al horno con espárragos y limón",
        "imagen_url": "https://images.unsplash.com/photo-1676300185165-3f543c1fcb72?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=600",
        "tiempo_comida": "Comida",
        "goal_tags": ["maintenance", "bulk"],
        "categoria_tags": ["Alto en proteína"],
        "ingredientes": [
            {"alimento": "Filete de salmón", "cantidad_g": 180},
            {"alimento": "Espárragos", "cantidad_g": 120},
            {"alimento": "Limón", "cantidad_g": 20},
            {"alimento": "Aceite de oliva", "cantidad_g": 8},
        ],
        "instrucciones": "Coloca el salmón y los espárragos en una charola, rocía con aceite y jugo de limón, y hornea a 200°C por 15 minutos.",
        "kcal_aprox": 380,
    },
    {
        "nombre": "Tinga de pollo con tostadas horneadas",
        "imagen_url": "https://images.unsplash.com/photo-1788576999396-f73418a7f763?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=600",
        "tiempo_comida": "Comida",
        "goal_tags": ["maintenance", "bulk"],
        "categoria_tags": [],
        "ingredientes": [
            {"alimento": "Pechuga de pollo deshebrada", "cantidad_g": 150},
            {"alimento": "Jitomate", "cantidad_g": 100},
            {"alimento": "Cebolla", "cantidad_g": 40},
            {"alimento": "Chipotle adobado", "cantidad_g": 15},
            {"alimento": "Tostada horneada", "cantidad_g": 60},
        ],
        "instrucciones": "Sofríe cebolla y jitomate, agrega el chipotle y el pollo deshebrado. Cocina 10 minutos y sirve sobre tostadas horneadas.",
        "kcal_aprox": 390,
    },
    {
        "nombre": "Milanesa de pollo empanizada al horno",
        "imagen_url": "https://images.unsplash.com/photo-1775889325293-fd23980169bf?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=600",
        "tiempo_comida": "Comida",
        "goal_tags": ["maintenance", "bulk"],
        "categoria_tags": ["Alto en proteína"],
        "ingredientes": [
            {"alimento": "Pechuga de pollo", "cantidad_g": 180},
            {"alimento": "Pan molido integral", "cantidad_g": 30},
            {"alimento": "Huevo entero", "cantidad_g": 50},
            {"alimento": "Ensalada verde mixta", "cantidad_g": 100},
        ],
        "instrucciones": "Aplana la pechuga, pasa por huevo y pan molido, y hornea a 200°C por 20 minutos volteando a la mitad. Sirve con ensalada.",
        "kcal_aprox": 410,
    },
    {
        "nombre": "Arrachera con nopales asados",
        "imagen_url": "https://images.unsplash.com/photo-1598511756475-c722aeaf9ad5?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=600",
        "tiempo_comida": "Comida",
        "goal_tags": ["bulk", "maintenance"],
        "categoria_tags": ["Alto en proteína"],
        "ingredientes": [
            {"alimento": "Arrachera de res", "cantidad_g": 180},
            {"alimento": "Nopal asado", "cantidad_g": 150},
            {"alimento": "Cebolla asada", "cantidad_g": 40},
        ],
        "instrucciones": "Asa la arrachera a término medio y córtala en tiras. Sirve con nopales y cebolla asados.",
        "kcal_aprox": 440,
    },
    {
        "nombre": "Lentejas con plátano macho y verduras",
        "imagen_url": "https://images.unsplash.com/photo-1664339031004-9cfdf88b8017?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=600",
        "tiempo_comida": "Comida",
        "goal_tags": ["cut", "maintenance"],
        "categoria_tags": ["Bajo en grasa"],
        "ingredientes": [
            {"alimento": "Lenteja cocida", "cantidad_g": 200},
            {"alimento": "Plátano macho", "cantidad_g": 80},
            {"alimento": "Zanahoria", "cantidad_g": 60},
            {"alimento": "Cebolla", "cantidad_g": 30},
        ],
        "instrucciones": "Guisa las lentejas con zanahoria y cebolla por 15 minutos. Sirve con rebanadas de plátano macho frito con poco aceite.",
        "kcal_aprox": 360,
    },
    {
        "nombre": "Tacos de pescado empanizado al horno",
        "imagen_url": "https://images.unsplash.com/photo-1665401015549-712c0dc5ef85?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=600",
        "tiempo_comida": "Comida",
        "goal_tags": ["cut", "maintenance"],
        "categoria_tags": ["Bajo en grasa"],
        "ingredientes": [
            {"alimento": "Filete de pescado blanco", "cantidad_g": 180},
            {"alimento": "Pan molido integral", "cantidad_g": 25},
            {"alimento": "Tortilla de maíz", "cantidad_g": 90},
            {"alimento": "Col morada picada", "cantidad_g": 50},
        ],
        "instrucciones": "Empaniza el pescado y hornea a 200°C por 15 minutos. Arma los tacos con tortilla, pescado y col morada.",
        "kcal_aprox": 380,
    },
    {
        "nombre": "Bowl de quinoa con garbanzo y verduras asadas",
        "imagen_url": "https://images.unsplash.com/photo-1764674963000-0d113663bc0d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=600",
        "tiempo_comida": "Comida",
        "goal_tags": ["cut", "maintenance"],
        "categoria_tags": ["Bajo en grasa", "Ensaladas"],
        "ingredientes": [
            {"alimento": "Quinoa cocida", "cantidad_g": 120},
            {"alimento": "Garbanzo cocido", "cantidad_g": 100},
            {"alimento": "Calabacita asada", "cantidad_g": 80},
            {"alimento": "Pimiento asado", "cantidad_g": 60},
        ],
        "instrucciones": "Mezcla la quinoa con el garbanzo y las verduras asadas. Sirve tibio o frío según preferencia.",
        "kcal_aprox": 380,
    },
    {
        "nombre": "Camarones al ajillo con arroz blanco",
        "imagen_url": "https://images.unsplash.com/photo-1625943553852-781c6dd46faa?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=600",
        "tiempo_comida": "Comida",
        "goal_tags": ["maintenance", "bulk"],
        "categoria_tags": ["Alto en proteína"],
        "ingredientes": [
            {"alimento": "Camarón limpio", "cantidad_g": 180},
            {"alimento": "Ajo picado", "cantidad_g": 15},
            {"alimento": "Aceite de oliva", "cantidad_g": 10},
            {"alimento": "Arroz blanco cocido", "cantidad_g": 100},
        ],
        "instrucciones": "Saltea el ajo en aceite de oliva hasta dorar, agrega los camarones y cocina 4-5 minutos. Sirve sobre arroz blanco.",
        "kcal_aprox": 410,
    },
    # Cena
    {
        "nombre": "Crema de champiñones ligera",
        "imagen_url": "https://images.unsplash.com/photo-1643786661490-966f1877effa?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=600",
        "tiempo_comida": "Cena",
        "goal_tags": ["cut"],
        "categoria_tags": ["Bajo en grasa"],
        "ingredientes": [
            {"alimento": "Champiñón fileteado", "cantidad_g": 200},
            {"alimento": "Cebolla", "cantidad_g": 40},
            {"alimento": "Leche descremada", "cantidad_g": 150},
            {"alimento": "Caldo de verduras", "cantidad_g": 200},
        ],
        "instrucciones": "Sofríe champiñones y cebolla, agrega el caldo y cocina 10 minutos. Licúa con la leche descremada hasta obtener textura cremosa.",
        "kcal_aprox": 160,
    },
    {
        "nombre": "Ensalada de espinaca con nuez y queso panela",
        "imagen_url": "https://images.unsplash.com/photo-1646487793655-bbf280273d2f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=600",
        "tiempo_comida": "Cena",
        "goal_tags": ["cut", "maintenance"],
        "categoria_tags": ["Ensaladas", "Bajo en grasa"],
        "ingredientes": [
            {"alimento": "Espinaca fresca", "cantidad_g": 100},
            {"alimento": "Nuez", "cantidad_g": 15},
            {"alimento": "Queso panela", "cantidad_g": 40},
            {"alimento": "Vinagreta ligera", "cantidad_g": 15},
        ],
        "instrucciones": "Mezcla la espinaca con la nuez y el queso panela en cubos. Aliña con la vinagreta justo antes de servir.",
        "kcal_aprox": 240,
    },
    {
        "nombre": "Tostadas de atún con aguacate",
        "imagen_url": "https://images.unsplash.com/photo-1604497181015-76590d828b75?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=600",
        "tiempo_comida": "Cena",
        "goal_tags": ["cut", "maintenance"],
        "categoria_tags": ["Alto en proteína"],
        "ingredientes": [
            {"alimento": "Atún en agua", "cantidad_g": 120},
            {"alimento": "Aguacate", "cantidad_g": 50},
            {"alimento": "Tostada horneada", "cantidad_g": 60},
            {"alimento": "Jitomate picado", "cantidad_g": 40},
        ],
        "instrucciones": "Mezcla el atún escurrido con el aguacate machacado y el jitomate. Sirve sobre las tostadas horneadas.",
        "kcal_aprox": 300,
    },
    {
        "nombre": "Sopa de calabaza con jengibre",
        "imagen_url": "https://images.unsplash.com/photo-1605034997223-1a4819bb58cf?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=600",
        "tiempo_comida": "Cena",
        "goal_tags": ["cut"],
        "categoria_tags": ["Bajo en grasa"],
        "ingredientes": [
            {"alimento": "Calabaza de castilla", "cantidad_g": 250},
            {"alimento": "Jengibre fresco", "cantidad_g": 10},
            {"alimento": "Cebolla", "cantidad_g": 30},
            {"alimento": "Caldo de verduras", "cantidad_g": 200},
        ],
        "instrucciones": "Cuece la calabaza con cebolla, jengibre y caldo por 20 minutos. Licúa hasta obtener una crema tersa.",
        "kcal_aprox": 140,
    },
    {
        "nombre": "Wrap de pavo con vegetales frescos",
        "imagen_url": "https://images.unsplash.com/photo-1762631383815-784c04533802?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=600",
        "tiempo_comida": "Cena",
        "goal_tags": ["cut", "maintenance"],
        "categoria_tags": ["Alto en proteína"],
        "ingredientes": [
            {"alimento": "Pechuga de pavo rebanada", "cantidad_g": 100},
            {"alimento": "Tortilla integral", "cantidad_g": 50},
            {"alimento": "Lechuga", "cantidad_g": 30},
            {"alimento": "Jitomate", "cantidad_g": 40},
        ],
        "instrucciones": "Rellena la tortilla integral con el pavo, la lechuga y el jitomate. Enrolla firmemente y corta a la mitad.",
        "kcal_aprox": 280,
    },
    # ---------- LOTE 2 (Mis catálogos) ----------
    # Desayuno
    {
        "nombre": "Tortilla de huevo con champiñones al ajillo",
        "imagen_url": "https://images.unsplash.com/photo-1668283653825-37b80f055b05?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=600",
        "tiempo_comida": "Desayuno",
        "goal_tags": ["cut", "maintenance"],
        "categoria_tags": ["Alto en proteína"],
        "ingredientes": [
            {"alimento": "Huevo entero", "cantidad_g": 120},
            {"alimento": "Champiñón fileteado", "cantidad_g": 80},
            {"alimento": "Ajo picado", "cantidad_g": 10},
            {"alimento": "Aceite de oliva", "cantidad_g": 5},
        ],
        "instrucciones": "Saltea el ajo y los champiñones en aceite de oliva hasta dorar. Agrega el huevo batido y cuece a fuego medio hasta cuajar.",
        "kcal_aprox": 260,
    },
    {
        "nombre": "Pan integral con aceite de oliva y jitomate",
        "imagen_url": "https://images.unsplash.com/photo-1702742803242-2ffd88953909?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=600",
        "tiempo_comida": "Desayuno",
        "goal_tags": ["cut", "maintenance"],
        "categoria_tags": ["Bajo en grasa"],
        "ingredientes": [
            {"alimento": "Pan integral", "cantidad_g": 60},
            {"alimento": "Jitomate en rodajas", "cantidad_g": 80},
            {"alimento": "Aceite de oliva", "cantidad_g": 8},
            {"alimento": "Orégano seco", "cantidad_g": 1},
        ],
        "instrucciones": "Tuesta el pan integral, rocía con aceite de oliva y cubre con rodajas de jitomate. Espolvorea orégano al final.",
        "kcal_aprox": 220,
    },
    {
        "nombre": "Yogur griego con nuez y miel de abeja",
        "imagen_url": "https://images.unsplash.com/photo-1633893215265-4763142f9b57?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=600",
        "tiempo_comida": "Desayuno",
        "goal_tags": ["maintenance", "bulk"],
        "categoria_tags": ["Alto en proteína"],
        "ingredientes": [
            {"alimento": "Yogur griego natural", "cantidad_g": 200},
            {"alimento": "Nuez", "cantidad_g": 20},
            {"alimento": "Miel de abeja", "cantidad_g": 12},
        ],
        "instrucciones": "Sirve el yogur en un tazón, agrega la nuez picada encima y termina con un hilo de miel.",
        "kcal_aprox": 300,
    },
    {
        "nombre": "Malteada de avena, cacao y plátano",
        "imagen_url": "https://images.unsplash.com/photo-1740637372899-e27569049917?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=600",
        "tiempo_comida": "Desayuno",
        "goal_tags": ["bulk"],
        "categoria_tags": ["Nuevas"],
        "ingredientes": [
            {"alimento": "Avena en hojuelas", "cantidad_g": 40},
            {"alimento": "Plátano", "cantidad_g": 100},
            {"alimento": "Cacao en polvo sin azúcar", "cantidad_g": 10},
            {"alimento": "Leche entera", "cantidad_g": 250},
        ],
        "instrucciones": "Licúa todos los ingredientes hasta obtener una mezcla homogénea y espumosa. Sirve frío.",
        "kcal_aprox": 380,
    },
    {
        "nombre": "Yogur con cúrcuma, canela y miel",
        "imagen_url": "https://images.unsplash.com/photo-1610450622921-73466281ceb3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=600",
        "tiempo_comida": "Desayuno",
        "goal_tags": ["cut", "maintenance"],
        "categoria_tags": ["Bajo en grasa"],
        "ingredientes": [
            {"alimento": "Yogur natural bajo en grasa", "cantidad_g": 180},
            {"alimento": "Cúrcuma en polvo", "cantidad_g": 2},
            {"alimento": "Canela en polvo", "cantidad_g": 2},
            {"alimento": "Miel de abeja", "cantidad_g": 8},
        ],
        "instrucciones": "Mezcla el yogur con la cúrcuma y la canela hasta integrar bien. Termina con un hilo de miel.",
        "kcal_aprox": 150,
    },
    {
        "nombre": "Sándwich integral de huevo y aguacate",
        "imagen_url": "https://images.unsplash.com/photo-1687276287139-88f7333c8ca4?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=600",
        "tiempo_comida": "Desayuno",
        "goal_tags": ["maintenance", "bulk"],
        "categoria_tags": ["Alto en proteína"],
        "ingredientes": [
            {"alimento": "Pan integral", "cantidad_g": 70},
            {"alimento": "Huevo entero", "cantidad_g": 100},
            {"alimento": "Aguacate", "cantidad_g": 50},
        ],
        "instrucciones": "Cocina el huevo a tu gusto (cocido o estrellado). Unta el aguacate en el pan y arma el sándwich con el huevo.",
        "kcal_aprox": 340,
    },
    # Colación
    {
        "nombre": "Barra de amaranto casera",
        "imagen_url": "https://images.unsplash.com/photo-1634582870449-90577753e6e3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=600",
        "tiempo_comida": "Colación",
        "goal_tags": ["maintenance", "bulk"],
        "categoria_tags": [],
        "ingredientes": [
            {"alimento": "Amaranto tostado", "cantidad_g": 40},
            {"alimento": "Miel de abeja", "cantidad_g": 20},
            {"alimento": "Nuez picada", "cantidad_g": 10},
        ],
        "instrucciones": "Calienta la miel hasta que espese ligeramente, mezcla con el amaranto y la nuez, y compacta en un molde. Deja enfriar y corta en barras.",
        "kcal_aprox": 180,
    },
    {
        "nombre": "Requesón con mango y chía",
        "imagen_url": "https://images.unsplash.com/photo-1560717845-968823efbee1?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=600",
        "tiempo_comida": "Colación",
        "goal_tags": ["cut", "maintenance"],
        "categoria_tags": ["Alto en proteína"],
        "ingredientes": [
            {"alimento": "Requesón", "cantidad_g": 120},
            {"alimento": "Mango picado", "cantidad_g": 80},
            {"alimento": "Semillas de chía", "cantidad_g": 8},
        ],
        "instrucciones": "Mezcla el requesón con el mango picado y espolvorea las semillas de chía encima.",
        "kcal_aprox": 190,
    },
    {
        "nombre": "Apio con hummus casero",
        "imagen_url": "https://images.unsplash.com/photo-1708436476465-0938f4e28836?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=600",
        "tiempo_comida": "Colación",
        "goal_tags": ["cut"],
        "categoria_tags": ["Bajo en grasa"],
        "ingredientes": [
            {"alimento": "Apio en bastones", "cantidad_g": 150},
            {"alimento": "Garbanzo cocido", "cantidad_g": 80},
            {"alimento": "Tahini", "cantidad_g": 10},
            {"alimento": "Limón", "cantidad_g": 10},
        ],
        "instrucciones": "Licúa el garbanzo con tahini y jugo de limón hasta obtener un hummus cremoso. Sirve con los bastones de apio para untar.",
        "kcal_aprox": 140,
    },
    {
        "nombre": "Té verde con almendras tostadas",
        "imagen_url": "https://images.unsplash.com/photo-1589869092622-0a45b2c7e9bb?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=600",
        "tiempo_comida": "Colación",
        "goal_tags": ["cut"],
        "categoria_tags": [],
        "ingredientes": [
            {"alimento": "Té verde", "cantidad_g": 250},
            {"alimento": "Almendra", "cantidad_g": 20},
        ],
        "instrucciones": "Prepara el té verde y sirve acompañado de un puñado de almendras tostadas.",
        "kcal_aprox": 130,
    },
    {
        "nombre": "Yogur griego con nuez de la India",
        "imagen_url": "https://images.unsplash.com/photo-1626697556426-8a55a8af4999?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=600",
        "tiempo_comida": "Colación",
        "goal_tags": ["maintenance", "bulk"],
        "categoria_tags": ["Alto en proteína"],
        "ingredientes": [
            {"alimento": "Yogur griego entero", "cantidad_g": 150},
            {"alimento": "Nuez de la india", "cantidad_g": 20},
        ],
        "instrucciones": "Sirve el yogur en un tazón y agrega la nuez de la india encima.",
        "kcal_aprox": 220,
    },
    # Comida
    {
        "nombre": "Ensalada César con pollo y aderezo ligero",
        "imagen_url": "https://images.unsplash.com/photo-1605291535065-e1d52d2b264a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=600",
        "tiempo_comida": "Comida",
        "goal_tags": ["cut", "maintenance"],
        "categoria_tags": ["Ensaladas", "Alto en proteína"],
        "ingredientes": [
            {"alimento": "Pechuga de pollo a la plancha", "cantidad_g": 150},
            {"alimento": "Lechuga romana", "cantidad_g": 100},
            {"alimento": "Queso parmesano", "cantidad_g": 15},
            {"alimento": "Aderezo César ligero", "cantidad_g": 20},
        ],
        "instrucciones": "Corta la pechuga en tiras y mezcla con la lechuga, el queso parmesano y el aderezo ligero.",
        "kcal_aprox": 340,
    },
    {
        "nombre": "Pescado al horno con aceite de oliva y hierbas",
        "imagen_url": "https://images.unsplash.com/photo-1611507775040-6af3f6a18656?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=600",
        "tiempo_comida": "Comida",
        "goal_tags": ["cut", "maintenance"],
        "categoria_tags": ["Bajo en grasa", "Alto en proteína"],
        "ingredientes": [
            {"alimento": "Filete de pescado blanco", "cantidad_g": 200},
            {"alimento": "Aceite de oliva", "cantidad_g": 10},
            {"alimento": "Romero fresco", "cantidad_g": 3},
            {"alimento": "Limón", "cantidad_g": 20},
        ],
        "instrucciones": "Coloca el pescado en una charola, rocía con aceite y jugo de limón, y espolvorea romero. Hornea a 200°C por 15 minutos.",
        "kcal_aprox": 280,
    },
    {
        "nombre": "Milanesa de res al horno con ensalada fresca",
        "imagen_url": "https://images.unsplash.com/photo-1761582861462-ee72cf21336e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=600",
        "tiempo_comida": "Comida",
        "goal_tags": ["maintenance", "bulk"],
        "categoria_tags": ["Alto en proteína"],
        "ingredientes": [
            {"alimento": "Milanesa de res", "cantidad_g": 180},
            {"alimento": "Pan molido integral", "cantidad_g": 30},
            {"alimento": "Ensalada verde mixta", "cantidad_g": 100},
        ],
        "instrucciones": "Empaniza la milanesa y hornea a 200°C por 20 minutos volteando a la mitad. Sirve con ensalada fresca.",
        "kcal_aprox": 440,
    },
    {
        "nombre": "Salmón al horno con cúrcuma y brócoli",
        "imagen_url": "https://images.unsplash.com/photo-1601316585772-ba1e6dae9cfc?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=600",
        "tiempo_comida": "Comida",
        "goal_tags": ["maintenance", "bulk"],
        "categoria_tags": ["Alto en proteína"],
        "ingredientes": [
            {"alimento": "Filete de salmón", "cantidad_g": 180},
            {"alimento": "Cúrcuma en polvo", "cantidad_g": 3},
            {"alimento": "Brócoli", "cantidad_g": 120},
        ],
        "instrucciones": "Sazona el salmón con cúrcuma y hornea junto con el brócoli a 200°C por 15 minutos.",
        "kcal_aprox": 400,
    },
    {
        "nombre": "Pasta integral con jitomate, ajo y albahaca",
        "imagen_url": "https://images.unsplash.com/photo-1598866594230-a7c12756260f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=600",
        "tiempo_comida": "Comida",
        "goal_tags": ["maintenance", "bulk"],
        "categoria_tags": [],
        "ingredientes": [
            {"alimento": "Pasta integral", "cantidad_g": 100},
            {"alimento": "Jitomate", "cantidad_g": 150},
            {"alimento": "Ajo picado", "cantidad_g": 10},
            {"alimento": "Albahaca fresca", "cantidad_g": 5},
        ],
        "instrucciones": "Cuece la pasta al dente. Sofríe el ajo, agrega el jitomate picado y cocina 10 minutos. Mezcla con la pasta y termina con albahaca fresca.",
        "kcal_aprox": 380,
    },
    {
        "nombre": "Ensalada griega con queso feta y aceitunas",
        "imagen_url": "https://images.unsplash.com/photo-1606735584785-1848fdcaea57?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=600",
        "tiempo_comida": "Comida",
        "goal_tags": ["cut", "maintenance"],
        "categoria_tags": ["Ensaladas"],
        "ingredientes": [
            {"alimento": "Pepino", "cantidad_g": 100},
            {"alimento": "Jitomate", "cantidad_g": 100},
            {"alimento": "Queso feta", "cantidad_g": 40},
            {"alimento": "Aceituna negra", "cantidad_g": 20},
        ],
        "instrucciones": "Corta el pepino y el jitomate en cubos, mezcla con el queso feta y las aceitunas. Aliña con aceite de oliva al gusto.",
        "kcal_aprox": 250,
    },
    {
        "nombre": "Tazón de vegetales salteados con tofu",
        "imagen_url": "https://images.unsplash.com/photo-1657251867365-912394b305ea?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=600",
        "tiempo_comida": "Comida",
        "goal_tags": ["cut", "maintenance"],
        "categoria_tags": ["Bajo en grasa"],
        "ingredientes": [
            {"alimento": "Tofu firme", "cantidad_g": 150},
            {"alimento": "Pimiento", "cantidad_g": 80},
            {"alimento": "Calabacita", "cantidad_g": 80},
            {"alimento": "Salsa de soya baja en sodio", "cantidad_g": 10},
        ],
        "instrucciones": "Saltea el tofu en cubos hasta dorar, agrega los vegetales y cocina 5 minutos más. Termina con la salsa de soya.",
        "kcal_aprox": 300,
    },
    {
        "nombre": "Sopa de lentejas al estilo mediterráneo",
        "imagen_url": "https://images.unsplash.com/photo-1512003867696-6d5ce6835040?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=600",
        "tiempo_comida": "Comida",
        "goal_tags": ["cut", "maintenance"],
        "categoria_tags": ["Bajo en grasa"],
        "ingredientes": [
            {"alimento": "Lenteja cocida", "cantidad_g": 200},
            {"alimento": "Zanahoria", "cantidad_g": 60},
            {"alimento": "Apio", "cantidad_g": 40},
            {"alimento": "Aceite de oliva", "cantidad_g": 8},
        ],
        "instrucciones": "Sofríe zanahoria y apio en aceite de oliva, agrega las lentejas y un poco de caldo. Cocina 15 minutos a fuego bajo.",
        "kcal_aprox": 320,
    },
    {
        "nombre": "Pechuga con jengibre, ajo y verduras salteadas",
        "imagen_url": "https://images.unsplash.com/photo-1762305195108-be2a505b4b59?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=600",
        "tiempo_comida": "Comida",
        "goal_tags": ["cut", "maintenance"],
        "categoria_tags": ["Alto en proteína"],
        "ingredientes": [
            {"alimento": "Pechuga de pollo en tiras", "cantidad_g": 180},
            {"alimento": "Jengibre fresco", "cantidad_g": 10},
            {"alimento": "Ajo picado", "cantidad_g": 10},
            {"alimento": "Verduras mixtas", "cantidad_g": 150},
        ],
        "instrucciones": "Saltea el pollo con jengibre y ajo hasta dorar. Agrega las verduras y cocina 5 minutos más a fuego alto.",
        "kcal_aprox": 340,
    },
    # Cena
    {
        "nombre": "Crema de espinaca ligera con pechuga",
        "imagen_url": "https://images.unsplash.com/photo-1626200419199-391ae4be7a41?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=600",
        "tiempo_comida": "Cena",
        "goal_tags": ["cut"],
        "categoria_tags": ["Bajo en grasa", "Alto en proteína"],
        "ingredientes": [
            {"alimento": "Espinaca fresca", "cantidad_g": 150},
            {"alimento": "Pechuga de pollo deshebrada", "cantidad_g": 100},
            {"alimento": "Leche descremada", "cantidad_g": 150},
            {"alimento": "Cebolla", "cantidad_g": 30},
        ],
        "instrucciones": "Cuece la espinaca con cebolla, licúa con la leche descremada hasta obtener una crema. Sirve con el pollo deshebrado encima.",
        "kcal_aprox": 220,
    },
    {
        "nombre": "Ensalada de garbanzo, pepino y jitomate",
        "imagen_url": "https://images.unsplash.com/photo-1719196339826-c66c13ad5b86?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=600",
        "tiempo_comida": "Cena",
        "goal_tags": ["cut", "maintenance"],
        "categoria_tags": ["Ensaladas", "Bajo en grasa"],
        "ingredientes": [
            {"alimento": "Garbanzo cocido", "cantidad_g": 150},
            {"alimento": "Pepino", "cantidad_g": 80},
            {"alimento": "Jitomate", "cantidad_g": 80},
            {"alimento": "Aceite de oliva", "cantidad_g": 8},
        ],
        "instrucciones": "Mezcla el garbanzo con el pepino y el jitomate picados. Aliña con aceite de oliva y sal al gusto.",
        "kcal_aprox": 280,
    },
    {
        "nombre": "Tortilla de claras con champiñones y queso panela",
        "imagen_url": "https://images.unsplash.com/photo-1665206231479-6bff0bdcd51d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=600",
        "tiempo_comida": "Cena",
        "goal_tags": ["cut"],
        "categoria_tags": ["Bajo en grasa", "Alto en proteína"],
        "ingredientes": [
            {"alimento": "Clara de huevo", "cantidad_g": 180},
            {"alimento": "Champiñón fileteado", "cantidad_g": 60},
            {"alimento": "Queso panela", "cantidad_g": 30},
        ],
        "instrucciones": "Saltea los champiñones, agrega las claras batidas y cocina a fuego medio. Añade el queso panela antes de doblar.",
        "kcal_aprox": 210,
    },
    {
        "nombre": "Verduras asadas con queso feta",
        "imagen_url": "https://images.unsplash.com/photo-1657195721656-8254f104f289?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=600",
        "tiempo_comida": "Cena",
        "goal_tags": ["cut", "maintenance"],
        "categoria_tags": ["Bajo en grasa"],
        "ingredientes": [
            {"alimento": "Calabacita", "cantidad_g": 100},
            {"alimento": "Pimiento", "cantidad_g": 80},
            {"alimento": "Berenjena", "cantidad_g": 80},
            {"alimento": "Queso feta", "cantidad_g": 30},
        ],
        "instrucciones": "Corta las verduras y hornea a 200°C por 20 minutos. Sirve con el queso feta desmoronado encima.",
        "kcal_aprox": 200,
    },
    {
        "nombre": "Tofu revuelto con jitomate y cebolla",
        "imagen_url": "https://images.unsplash.com/photo-1622912789333-ba8bf8242e27?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=600",
        "tiempo_comida": "Cena",
        "goal_tags": ["cut", "maintenance"],
        "categoria_tags": ["Bajo en grasa"],
        "ingredientes": [
            {"alimento": "Tofu firme desmoronado", "cantidad_g": 150},
            {"alimento": "Jitomate picado", "cantidad_g": 80},
            {"alimento": "Cebolla picada", "cantidad_g": 30},
            {"alimento": "Cúrcuma en polvo", "cantidad_g": 2},
        ],
        "instrucciones": "Sofríe la cebolla y el jitomate, agrega el tofu desmoronado y la cúrcuma. Cocina 5-7 minutos revolviendo.",
        "kcal_aprox": 190,
    },
]


def seed_recipes():
    """Inserta cualquier receta de RECIPES cuyo nombre todavía no exista en la
    base (entre las de banco, created_by=null) — permite agregar lotes nuevos
    a esta lista sin duplicar las ya sembradas ni requerir un reset de base."""
    Base.metadata.create_all(bind=engine)
    db = SessionLocal()
    existing_names = {n for (n,) in db.query(Recipe.nombre).filter(Recipe.created_by.is_(None)).all()}
    to_insert = [item for item in RECIPES if item["nombre"] not in existing_names]
    if not to_insert:
        print(f"Recetas ya sembradas — {len(existing_names)} encontradas. Saltando.")
        db.close()
        return
    for item in to_insert:
        db.add(Recipe(created_by=None, **item))
    db.commit()
    db.close()
    print(f"Semilla de recetas: {len(to_insert)} nuevas insertadas ({len(existing_names)} ya existían).")


if __name__ == "__main__":
    seed_recipes()
